# -*- coding: utf-8 -*-
"""Name_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rcxTqg0GiPFwTsSHMCG5h_e97MRrpEE
"""

!pip3 install transformers

import numpy as np
import pandas as pd
from transformers import pipeline

nlp = pipeline("ner", model='dslim/bert-base-NER-uncased')

text_without_name = ""
#names_total = []
with open("./test-transcript.txt", "r") as f:
  for i in f.readlines():
    print(i)
    text = i
    ner = nlp(i, grouped_entities=True)
    print(ner)
    if ner != []:
      for j in ner:
        if j['entity_group'] == 'PER':
          print(j['word'])
          start = int(j['start'])
          finish = int(j['end'])
          text = text[:start] + 'x'*(finish - start) + text[finish:]
    text_without_name += (text + '\n')

text_file = open("test-transcript-without-name.txt", "w")
n = text_file.write(text_without_name)
text_file.close()

text_without_name = ""
names_total = []
nlp = pipeline("ner")
with open("./test-transcript-2.txt", "r") as f:
  for i in f.readlines():
    print(i)
    text = i
    names = []
    ner = nlp(i)
    print(ner)
    if ner != []:
      for j in ner:
        if j['entity'] == 'I-PER':
          print(j['word'])
          start = int(j['start'])
          finish = int(j['end'])
          text = text[:start] + 'x'*(finish - start) + text[finish:]
    text_without_name += (text + '\n')

text_file = open("test-transcript-2-without-name.txt", "w")
n = text_file.write(text_without_name)
text_file.close()

nlp('GW: My name is mathew I am currently working on my undergrad i\'m studying is like a cognitive psychology.')

'MF: As you can probably see from my little zoom tag my name\'s matt.'.title()

